Job manager actions view
MapColonies/discrete-layer-client pull request #246
Opened 2022-01-04 09:34 UTC by assafchamoy

2022-01-09 15:08 UTC, alebinson requested changes
Looks good.
There are a few comments(mostly cosmetics)

2022-01-09 15:08 UTC, alebinson commented on src/discrete-layer/components/system-status/cell-renderer/status.cell-renderer.css
> +  /* padding:2px; */
remove unneeded comment

2022-01-09 15:08 UTC, alebinson commented on src/discrete-layer/components/system-status/jobs-dialog.css
> +  width: 20px!important;
add " " space

2022-01-09 15:08 UTC, alebinson commented on src/discrete-layer/components/system-status/jobs-dialog.css
> +  height: 30px!important;
add " " space

2022-01-09 15:08 UTC, alebinson commented on src/discrete-layer/components/system-status/jobs-dialog.tsx
> +    actions[0].group = actions[0].group.map((action) => {
why [0]?

2022-01-09 15:08 UTC, alebinson commented on src/discrete-layer/components/system-status/jobs-dialog.tsx
> +              // width: 'calc(100% - 100px)',
remove unneeded comment

2022-01-10 09:06 UTC, assafchamoy commented on src/discrete-layer/components/system-status/jobs-dialog.css
> +  width: 20px!important;
OK

2022-01-10 09:06 UTC, assafchamoy commented on src/discrete-layer/components/system-status/jobs-dialog.css
> +  height: 30px!important;
OK

2022-01-10 09:07 UTC, assafchamoy commented on src/discrete-layer/components/system-status/cell-renderer/status.cell-renderer.css
> +  /* padding:2px; */
OK

2022-01-10 09:08 UTC, assafchamoy commented on src/discrete-layer/components/system-status/jobs-dialog.tsx
> +              // width: 'calc(100% - 100px)',
OK

2022-01-10 09:31 UTC, assafchamoy commented on src/discrete-layer/components/system-status/jobs-dialog.tsx
> +    actions[0].group = actions[0].group.map((action) => {
That is very correct :)

2022-01-10 09:39 UTC, alebinson commented on src/discrete-layer/components/system-status/jobs-dialog.tsx
> +    actions[0].group = actions[0].group.map((action) => {
Ok

2022-01-10 09:40 UTC, alebinson approved these changes
Good job

2022-01-10 09:45 UTC, merged