feat: metadata exporter basic concept
MapColonies/discrete-layer-client pull request #351
Opened 2022-09-07 12:52 UTC by assafchamoy

2022-09-07 13:41 UTC, alebinson requested changes
see my comments

2022-09-07 13:41 UTC, alebinson commented on src/common/i18n/en.json
> +  "action.export-metadata.tooltip": "Export Metadata",
Terminology should be **Save**

2022-09-07 13:41 UTC, alebinson commented on src/common/i18n/he.json
> +  "action.export-metadata.tooltip": "יצא קובץ מטא-דאטה",
שמור ...

2022-09-07 13:41 UTC, alebinson commented on src/discrete-layer/components/layer-details/utils.ts
> +  const link = document.createElement('a');
added <a> element should be deleted

2022-09-11 18:15 UTC, EllaMartirosyan commented on src/discrete-layer/models/userStore.ts
> +      [UserAction.ENTITY_ACTION_BESTRECORD_SAVE_METADATA]: true,
Duplicate line - 76 & 79

2022-09-11 18:16 UTC, EllaMartirosyan commented on src/discrete-layer/models/userStore.ts
> +      [UserAction.ENTITY_ACTION_BESTRECORD_SAVE_METADATA]: true,
Duplicate line - 109 & 113

2022-09-11 18:24 UTC, EllaMartirosyan commented on src/discrete-layer/views/components/action-resolver.component.tsx
> +        case 'QuantizedMeshBestRecord.save-metadata':
You can combine multiple cases with the same result

2022-09-12 10:52 UTC, alebinson approved these changes
gr8!

2022-09-12 11:43 UTC, merged