Lookup tables
MapColonies/discrete-layer-client pull request #403
Opened 2023-01-02 12:35 UTC by ronnahom96

2023-01-02 13:54 UTC, assafchamoy requested changes
Nice!, see my comments

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/components/layer-details/field-value-presentors/lookup.options-presentor.tsx
> +        {"tooltip test value"}
Handle this condition differently.. without the hard coded value, take inspiration from enum.value-presentor.tsx

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/components/layer-details/field-value-presentors/lookup.options-presentor.tsx
> +  } else {
unneeded else after return

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/components/layer-details/utils.ts
> +export const getBasicType = (fieldName: FieldInfoName, typename: string, lookupTableKey: string | null = null): string => {
change to:
lookupTableKey?: string
 so you wont need the default assertion to null.
 then check for existence.

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/models/FieldConfigModel.base.ts
> +    subFields: types.union(types.undefined, types.null, types.array(types.late((): any => FieldConfigModel))), default: types.union(types.undefined, types.null, types.string),
Unnecessary change here.

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/views/components/data-fetchers/lookup-tables-fetcher.component.tsx
> +      console.log(lookupTablesData)
remove console.log

2023-01-02 13:54 UTC, assafchamoy commented on src/App.tsx
> +import React, { useState, useLayoutEffect, useEffect } from 'react';
unneeded indent

2023-01-02 13:54 UTC, assafchamoy commented on src/App.tsx
> +  const customThemeProps: Record<string, string> = {};
unneeded indent

2023-01-02 13:54 UTC, assafchamoy commented on src/discrete-layer/components/layer-details/field-value-presentors/lookup.options-presentor.tsx
> +  if (!lookupTablesData) return <></>;
Is there a reason to return React Fragment instead of null here?
If not, change to null :)

2023-01-15 08:21 UTC, alebinson requested changes
see my comments

2023-01-15 08:21 UTC, alebinson commented on src/discrete-layer/components/layer-details/field-value-presentors/enum.value-presentor.tsx
> -    } else if (Array.isArray(innerValue)) {
Not relevant

2023-01-15 08:21 UTC, alebinson commented on src/discrete-layer/components/layer-details/field-value-presentors/lookup.options-presentor.tsx
> +    } else if (Array.isArray(innerValue)) {
remove from here

2023-01-15 08:25 UTC, alebinson approved these changes
just fixe what's commented by me

2023-01-15 09:13 UTC, merged