fix(selectio): grid row selection and slight refactor
MapColonies/discrete-layer-client pull request #42
Opened 2021-01-05 09:35 UTC by alebinson

2021-01-06 15:13 UTC, alebinson commented
Controlling footprint outlineColor/outlineWidth(to avoid filling color) works **ONLY** for **polyline** footprint geojson presentation.

So, multypolygon should be converted to polyline in more accurate way. 

Current situation:
Footprints presented "**as is**" with random fill color

Proposition(by @asafMasa & @shaziri ):
Footprints with no fill but with random border colors and controlled width

Proposed action(by @alebinson ):
1. Approve PR (with review comments fixes)
2. Open an **new** issue to implement requested "transparent footprints" change

2021-01-07 09:03 UTC, asafMasa requested changes
👍

2021-01-07 11:48 UTC, alebinson commented on src/discrete-layer/components/layers-results/layers-results.tsx
> +const UPDATE_TIMEOUT = 0;
Done

2021-01-07 11:48 UTC, alebinson commented on src/discrete-layer/components/layers-results/layers-results.tsx
> +      // checkboxSelection: true,
Done

2021-01-07 11:50 UTC, alebinson commented on src/discrete-layer/components/map-container/map-container.tsx
> +        if(!resultsOpen){
Think it's minor, no need for my opinion

2021-01-07 11:53 UTC, alebinson commented on src/discrete-layer/components/map-container/selected-layers-container.tsx
> +        cacheRef.current = {};
Open an issue https://github.com/MapColonies/discrete-layer-client/issues/50

2021-01-07 14:49 UTC, asafMasa approved these changes

2021-01-07 14:49 UTC, merged